In [1]:
import pandas as pd

pd.read_csv("./data/IXIC-2023.csv")

               날짜         종가         시가         고가         저가      거래량    변동 %
0    2023- 12- 22  14,992.97  15,006.18  15,047.19  14,927.12  880.44M   0.19%
1    2023- 12- 21  14,963.87  14,923.14  14,970.81  14,837.47  945.08M   1.26%
2    2023- 12- 20  14,777.94  14,973.36  15,069.29  14,776.29    1.20B  -1.50%
3    2023- 12- 19  15,003.22  14,923.02  15,003.80  14,921.60    1.13B   0.66%
4    2023- 12- 18  14,904.81  14,814.02  14,938.04  14,811.82    1.15B   0.61%
..            ...        ...        ...        ...        ...      ...     ...
241  2023- 01- 09  10,635.65  10,662.11  10,807.26  10,619.12    1.04B   0.63%
242  2023- 01- 06  10,569.29  10,363.96  10,604.14  10,265.04  970.67M   2.56%
243  2023- 01- 05  10,305.24  10,390.31  10,393.22  10,295.25  957.48M  -1.47%
244  2023- 01- 04  10,458.76  10,467.82  10,515.22  10,337.64    1.04B   0.69%
245  2023- 01- 03  10,386.99  10,562.06  10,613.06  10,309.16  983.36M  -0.76%

[246 rows x 7 columns]

In [ ]:
print("test")