<h1> 달러, 나스닥 데이터 분석 테스트 </h1>

- 관련 유저스토리 : 트레이더는 수익률 3%를 위해 달러 N일 이상 상승 시 나스닥 상승 확률을 알기 원한다.
- 데이터: 달러, 나스닥 데이터
  - <b style="color:red">이슈: 데이터 종류 / 기간 / 단위</b>
    - <b>달러: DXY / 2023 / Daily</b>
    - <b>나스닥: IXIC / 2023 / Daily</b>

<h2>데이터 전처리</h2>

- 내용
  - 날짜로 인덱스 변경
  - 날짜(인덱스) 기준으로 오름차순 정렬
  - 상승 여부 컬럼(상승) 추가
  - 변동 비율 컬럼(비율) 추가

In [12]:
import pandas as pd

df_dxy = pd.read_csv("./data/DXY-2023.csv")
df_ixic = pd.read_csv("./data/IXIC-2023.csv")

df_dxy = df_dxy.set_index('날짜', drop=False)
df_dxy = df_dxy.sort_index()
df_dxy["상승"] = df_dxy["변동 %"].map(lambda x: float(x[:-1])>0)
df_dxy["비율"] = df_dxy["변동 %"].map(lambda x: float(x[:-1]))
# df_dxy

df_ixic = df_ixic.set_index('날짜', drop=False)
df_ixic = df_ixic.sort_index()
df_ixic["상승"] = df_ixic["변동 %"].map(lambda x: float(x[:-1])>0)
df_ixic["비율"] = df_ixic["변동 %"].map(lambda x: float(x[:-1]))
# df_ixic

In [13]:
df_dxy

,날짜,종가,시가,고가,저가,거래량,변동 %,상승,비율
날짜,,,,,,,,,
2023- 01- 01,2023- 01- 01,103.49,103.49,103.49,103.49,NaN,-0.03%,False,-0.03
2023- 01- 03,2023- 01- 03,104.52,103.66,104.86,103.47,NaN,0.99%,True,0.99
2023- 01- 04,2023- 01- 04,104.25,104.58,104.60,103.83,NaN,-0.26%,False,-0.26
2023- 01- 05,2023- 01- 05,105.04,104.07,105.27,103.99,NaN,0.76%,True,0.76
2023- 01- 06,2023- 01- 06,103.88,105.05,105.63,103.87,NaN,-1.11%,False,-1.11
...,...,...,...,...,...,...,...,...,...
2023- 12- 18,2023- 12- 18,102.56,102.59,102.63,102.38,NaN,-0.06%,False,-0.06
2023- 12- 19,2023- 12- 19,102.17,102.47,102.63,102.07,NaN,-0.38%,False,-0.38
2023- 12- 20,2023- 12- 20,102.41,102.19,102.54,102.16,NaN,0.24%,True,0.24
2023- 12- 21,2023- 12- 21,101.84,102.39,102.45,101.74,NaN,-0.55%,False,-0.55
2023- 12- 22,2023- 12- 22,101.70,101.76,101.89,101.43,NaN,-0.14%,False,-0.14

In [14]:
df_ixic

,날짜,종가,시가,고가,저가,거래량,변동 %,상승,비율
날짜,,,,,,,,,
2023- 01- 03,2023- 01- 03,"10,386.99","10,562.06","10,613.06","10,309.16",983.36M,-0.76%,False,-0.76
2023- 01- 04,2023- 01- 04,"10,458.76","10,467.82","10,515.22","10,337.64",1.04B,0.69%,True,0.69
2023- 01- 05,2023- 01- 05,"10,305.24","10,390.31","10,393.22","10,295.25",957.48M,-1.47%,False,-1.47
2023- 01- 06,2023- 01- 06,"10,569.29","10,363.96","10,604.14","10,265.04",970.67M,2.56%,True,2.56
2023- 01- 09,2023- 01- 09,"10,635.65","10,662.11","10,807.26","10,619.12",1.04B,0.63%,True,0.63
...,...,...,...,...,...,...,...,...,...
2023- 12- 18,2023- 12- 18,"14,904.81","14,814.02","14,938.04","14,811.82",1.15B,0.61%,True,0.61
2023- 12- 19,2023- 12- 19,"15,003.22","14,923.02","15,003.80","14,921.60",1.13B,0.66%,True,0.66
2023- 12- 20,2023- 12- 20,"14,777.94","14,973.36","15,069.29","14,776.29",1.20B,-1.50%,False,-1.50
2023- 12- 21,2023- 12- 21,"14,963.87","14,923.14","14,970.81","14,837.47",945.08M,1.26%,True,1.26
2023- 12- 22,2023- 12- 22,"14,992.97","15,006.18","15,047.19","14,927.12",880.44M,0.19%,True,0.19

- <b style="color:red">이슈: 같은 기간이지만 달러 데이터 개수와 나스닥 데이터 개수가 다름</b>
  - 달러 데이터가 더 많음
  - 날짜 데이터 차이
  - 달러 데이터는 나스닥 데이터를 포함함
  - <b>원인: 달러 데이터가 휴일에도 존재하는 경우가 있음</b>
  - <b>해결: 해당 날짜에 나스닥 데이터가 없는 달러 데이터는 사용할 것인지 판단 필요 (-> 테스트 필요)</b>

<h2>데이터 분석</h2>

<h3>1. 달러 상승 시, 다음날 나스닥 상승 확률</h3>

In [44]:
# 조건 : DXY, IXIC / 2023(~12.22) / Daily / 휴일 달러 데이터 포함
# !리팩터링 필요 (Dataframe 활용)

dict_dxy = df_dxy.to_dict(orient="records")

total = 0
up = 0

max_index = len(dict_dxy) - 1
for index, dxy in enumerate(dict_dxy):
    if dxy["상승"]:
        if index < max_index: # 예외처리 : 인덱스가 리스트 넘어가는 것 방지
            try: # 예외처리 : 휴일 나스닥 데이터 접근 제외
                next_index = index + 1
                next_date = dict_dxy[next_index]["날짜"]
                next_ixic = df_ixic.loc[next_date] # 예외발생 가능
                
                total = total + 1
                if next_ixic["상승"]:
                    up = up + 1
            except:
                pass # no data
                
up_per = round((up/total), 2) * 100
down_per = 100 - up_per

print("결과 1: 달러 상승 시, 다음날 나스닥 상승 확률 :", up_per)
print("결과 2: 달러 상승 시, 다음날 나스닥 하락(및 보합) 확률 :", down_per)

# (추가) 하락 시, 상승/하락 및 보합 확률
# (추가) 의미 있게 변동 확률 (=기준점 추가)
# 검증

결과 1: 달러 상승 시, 다음날 나스닥 상승 확률 : 54.0
결과 2: 달러 상승 시, 다음날 나스닥 하락(및 보합) 확률 : 46.0

In [26]:
# 달러 최대 연속 상승일 N 확인 (하락일?) (%?)
# dict_dxy = df_dxy.to_dict(orient="records")
# n = 0
# max_n = 0
# for x in dict_dxy:
#     if not x["상승"]:
#         if max_n < n:
#             max_n = n
#         n = 0
#     else:
#         n = n + 1
# print("최종 결과 최대 연속 상승일 :", max_n)